# Site settings
title: Rafik Farhad's CV 
description: ======='s CV
favicon: /assets/img/avatar.JPG
baseurl: 
url: RafikFarhad.github.io
#rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Rafik Farhad
  title: Student, ACM Programmer
  address: Sylhet, Bangladesh
  email: rafikfarhad@gmail.com
  link: RafikFarhad.github.io
  weibo:
  github: RafikFarhad
  linkedin: rafik-farhad-b6bb27103
  twitter: rafikfarhad
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: SUST Science Arena
      location: SUST, Sylhet
      title: Organization Secretary
      started: 2016
      duration: (2014 - Present)
      description: SUST Science Arena (SSA) is a science based voluntary organization in Shahjalal University of Science & Technology.

  educationHistory:
    - education1:
      organization: Shahjalal University of Science & Technology
      location: Sylhet, Bangladesh
      degree: Bachelor
      major: Computer Science & Engineering
      started: 2014
      duration: (2014 - 2018)
      description: Currently a student.
    - education2:
      organization: Brahmanbaria Govt. Collage
      location: Brahmanbaria, Bangladesh
      degree: Higher Secondary
      major: Intermediate of Science
      started: 2013
      duration: (2011 - 2013)
      description: 
    - education3:
      organization: Annada Govt. High School
      location: Brahmanbaria, Bangladesh
      degree: Primary, Secondary
      major: 
      started: 2001
      duration: (2001 - 2011)
      description: 


  languages:
    - language1:
      name: Bangla
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: C++
      percentage: 80%
    - skill2:
      name: JAVA
      percentage: 50%
    - skill3:
      name: PHP
      percentage: 50%
    - skill4:
      name: LARAVEL
      percentage: 50%
    - skill5:
      name: JavaFX
      percentage: 80%
