# Site settings
title: Rafik Farhad's CV 
description: ======='s CV
favicon: /assets/img/avatar.JPG
baseurl: RafikFarhad.github.io
url: RafikFarhad.github.io
#rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Rafik Farhad
  title: Student, ACM Programmer
  address: Sylhet, Bangladesh
  email: rafikfarhad@gmail.com
  link: RafikFarhad.github.io
  weibo:
  github: RafikFarhad
  linkedin: rafikfarhad
  twitter: rafikfarhad
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: SUST Science Arena
      location: SUST, Sylhet
      title: Organization Secretary
      started: 2016
      duration: (2014 - Present)
      description: SUST Science Arena (SSA) is a scince based voluntary organization in Shahjalal University of Science & Technology.

  educationHistory:
    - education1:
      organization: Shahjalal University of Science & Technology
      location: Sylhet, Bangladesh
      degree: BachelorComputer Science & Engineering
      major: Computer Science & Engineering
      started: 2014
      duration: (2014 - 2018)
      description: Currently a student.
  languages:
    - language1:
      name: Bangla
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: C++
      percentage: 80%
    - skill2:
      name: JAVA
      percentage: 50%
    - skill3:
      name: PHP
      percentage: 50%
    - skill4:
      name: LARAVEL
      percentage: 50%
    - skill5:
      name: JavaFX
      percentage: 80%
